version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usedcar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/usedcar
      JWT_SECRET: secret-key-change
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"

volumes:
  postgres_data:
