from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class LeadData(BaseModel):
    vin: str
    year: Optional[str] = None
    make: Optional[str] = None
    model: Optional[str] = None
    trim: Optional[str] = None
    mileage: Optional[int] = None
    color: Optional[str] = None
    transmission: Optional[str] = None
    fuelType: Optional[str] = None
    titleStatus: Optional[str] = None
    accidentHistory: Optional[str] = None
    numOwners: Optional[int] = None
    askingPrice: Optional[int] = None
    description: Optional[str] = None

COLORS = ["Pearl White", "Black", "Silver", "Gray", "White", "Red", "Blue", "Brown", "Gold", "Green", "Orange", "Yellow", "Beige", "Charcoal", "Midnight Blue", "Burgundy", "Tan", "Ivory", "Navy", "Slate"]

MAKES = ["Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Bugatti", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Dodge", "Ferrari", "Fiat", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "Infiniti", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lincoln", "Lucid", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "Mini", "Mitsubishi", "Nissan", "Polestar", "Porsche", "Ram", "Renault", "Rivian", "Rolls-Royce", "Saab", "Subaru", "Suzuki", "Tata", "Tesla", "Toyota", "Volkswagen", "Volvo", "Xpeng"]

MODELS = {
    "Acura": ["ILX", "MDX", "RDX", "TLX", "NSX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C"],
    "Aston Martin": ["DB11", "Vantage", "Rapide", "DBX"],
    "Audi": ["A3", "A4", "A6", "Q3", "Q5", "Q7", "A8"],
    "Bentley": ["Continental", "Mulsanne", "Bentayga"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7"],
    "Bugatti": ["Chiron", "Veyron"],
    "Buick": ["Regal", "LaCrosse", "Envision", "Encore", "Enclave"],
    "Cadillac": ["CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6"],
    "Chevrolet": ["Blazer", "Camaro", "Colorado", "Corvette", "Cruze", "Equinox", "Malibu", "Silverado 1500", "Traverse", "Tahoe"],
    "Chrysler": ["300", "Pacifica", "Prowler"],
    "Citroen": ["C3", "C4", "C5"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey"],
    "Ferrari": ["F8 Tributo", "F430", "F458", "FF", "Portofino"],
    "Fiat": ["500", "500X", "500L"],
    "Ford": ["Edge", "Escape", "Explorer", "F-150", "Mustang", "Ranger", "Bronco"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "GMC": ["Acadia", "Canyon", "Sierra 1500", "Terrain", "Yukon", "Yukon XL"],
    "Honda": ["Accord", "Civic", "CR-V", "Odyssey", "Pilot", "Ridgeline", "Fit", "Insight"],
    "Hyundai": ["Accent", "Elantra", "Ioniq", "Kona", "Palisade", "Santa Fe", "Sonata", "Tucson", "Venue"],
    "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX50", "QX60", "QX80"],
    "Jaguar": ["F-Pace", "F-Type", "I-Pace", "XE", "XF"],
    "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
    "Kia": ["Forte", "K5", "Niro", "Rio", "Seltos", "Sorento", "Sportage", "Stinger", "Telluride", "Sedona"],
    "Lamborghini": ["Aventador", "Huracán", "Urus"],
    "Land Rover": ["Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["ES", "GS", "IS", "GX", "LX", "LS", "NX", "RX", "UX"],
    "Lincoln": ["Aviator", "Corsair", "MKZ", "Navigator", "Continental"],
    "Lucid": ["Air"],
    "Maserati": ["Ghibli", "Levante", "Quattroporte", "MC20"],
    "Mazda": ["CX-3", "CX-30", "CX-50", "CX-5", "CX-9", "Mazda2", "Mazda3", "Mazda6", "MX-5 Miata"],
    "McLaren": ["570GT", "570S", "650S", "720S", "765LT"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "G-Class", "GLC", "GLE", "GLS"],
    "Mini": ["Clubman", "Countryman", "Hardtop"],
    "Mitsubishi": ["Eclipse", "Outlander", "Lancer", "Mirage"],
    "Nissan": ["Altima", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Z"],
    "Polestar": ["1", "2", "3", "4"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera"],
    "Ram": ["1500", "2500", "3500"],
    "Renault": ["Clio", "Espace", "Megane"],
    "Rivian": ["R1S", "R1T"],
    "Rolls-Royce": ["Ghost", "Phantom", "Cullinan"],
    "Saab": ["9-3", "9-5"],
    "Subaru": ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "WRX"],
    "Suzuki": ["Swift", "Vitara", "S-Cross"],
    "Tata": ["Nexon", "Harrier"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
    "Toyota": ["Camry", "Corolla", "GR Supra", "RAV4", "Highlander", "Prius", "4Runner", "Tacoma", "Tundra", "Sienna"],
    "Volkswagen": ["Golf", "Jetta", "Passat", "Tiguan", "Atlas", "ID.4", "ID.5"],
    "Volvo": ["S60", "S90", "XC40", "XC60", "XC90"],
    "Xpeng": ["G9", "P7", "P8"]
}

TRIMS = {
    "Acura|ILX": ["Standard", "Technology", "A-Spec"],
    "Acura|MDX": ["Standard", "Technology", "A-Spec", "Advance"],
    "Acura|RDX": ["Standard", "Technology", "A-Spec", "Advance"],
    "Acura|TLX": ["Standard", "Technology", "A-Spec", "PMC"],
    "Acura|NSX": ["Base", "Type-R"],
    "Alfa Romeo|Giulia": ["Standard", "Ti", "Quadrifoglio"],
    "Alfa Romeo|Stelvio": ["Standard", "Ti", "Quadrifoglio"],
    "Alfa Romeo|4C": ["Base", "Spider"],
    "Aston Martin|DB11": ["Base", "AMR"],
    "Aston Martin|Vantage": ["Base", "AMR"],
    "Aston Martin|Rapide": ["S"],
    "Aston Martin|DBX": ["Base", "AMR"],
    "Audi|A3": ["Standard", "Premium", "Premium Plus", "Prestige"],
    "Audi|A4": ["Standard", "Premium", "Premium Plus", "Prestige", "S4"],
    "Audi|A6": ["Premium", "Premium Plus", "Prestige", "S6"],
    "Audi|Q3": ["Standard", "Premium", "Premium Plus", "Prestige"],
    "Audi|Q5": ["Premium", "Premium Plus", "Prestige", "SQ5"],
    "Audi|Q7": ["Premium", "Premium Plus", "Prestige", "SQ7"],
    "Audi|A8": ["Standard", "Premium", "Prestige"],
    "Bentley|Continental": ["GT", "Flying Spur"],
    "Bentley|Mulsanne": ["Speed"],
    "Bentley|Bentayga": ["Base", "Speed"],
    "BMW|3 Series": ["320i", "330i", "340i", "M340i", "M3"],
    "BMW|5 Series": ["530i", "540i", "M550i", "M5"],
    "BMW|7 Series": ["740i", "750i", "M760i"],
    "BMW|X1": ["sDrive28i", "xDrive28i", "xDrive35i"],
    "BMW|X3": ["sDrive30i", "xDrive30i", "xDrive40i", "M40i", "M"],
    "BMW|X5": ["xDrive40i", "xDrive50i", "M50i", "M"],
    "BMW|X7": ["xDrive40i", "xDrive50i", "M50i"],
    "Bugatti|Chiron": ["Base", "Speed", "Super Sport"],
    "Bugatti|Veyron": ["Base", "Super Sport"],
    "Buick|Regal": ["Base", "Preferred", "GS"],
    "Buick|LaCrosse": ["Base", "Preferred", "Avenir"],
    "Buick|Envision": ["Preferred", "Essence", "Avenir"],
    "Buick|Encore": ["Preferred", "Essence", "Avenir"],
    "Buick|Enclave": ["Base", "Preferred", "Avenir"],
    "Cadillac|CT4": ["Luxury", "Premium", "Sport"],
    "Cadillac|CT5": ["Luxury", "Premium", "Platinum", "Sport"],
    "Cadillac|CT6": ["Base", "Luxury", "Premium"],
    "Cadillac|Escalade": ["Luxury", "Premium", "Platinum"],
    "Cadillac|XT4": ["Luxury", "Premium"],
    "Cadillac|XT5": ["Luxury", "Premium", "Platinum"],
    "Cadillac|XT6": ["Luxury", "Premium", "Platinum"],
    "Chevrolet|Blazer": ["L", "LT", "RS", "Premier"],
    "Chevrolet|Camaro": ["LT", "RS", "SS", "ZL1"],
    "Chevrolet|Colorado": ["Base", "LT", "Z71", "ZR2"],
    "Chevrolet|Corvette": ["Stingray", "Z06", "ZR2"],
    "Chevrolet|Cruze": ["L", "LT", "RS", "Premier"],
    "Chevrolet|Equinox": ["L", "LT", "RS", "LTZ"],
    "Chevrolet|Malibu": ["L", "LT", "RS", "Premier"],
    "Chevrolet|Silverado 1500": ["RST", "LTZ", "High Country", "Duramax"],
    "Chevrolet|Traverse": ["LS", "LT", "RS", "Premier"],
    "Chevrolet|Tahoe": ["LS", "LT", "RST", "High Country"],
    "Chrysler|300": ["Base", "Limited", "C"],
    "Chrysler|Pacifica": ["Touring", "Limited", "Pinnacle"],
    "Chrysler|Prowler": ["Base"],
    "Citroen|C3": ["Base", "Feel", "Shine"],
    "Citroen|C4": ["Live", "Shine", "Exclusive"],
    "Citroen|C5": ["Base", "Live", "Shine"],
    "Dodge|Charger": ["SE", "SXT", "R/T", "SRT", "Hellcat"],
    "Dodge|Challenger": ["SXT", "R/T", "SRT", "Hellcat", "Demon"],
    "Dodge|Durango": ["SXT", "R/T", "Citadel", "SRT"],
    "Dodge|Journey": ["SE", "SXT", "R/T"],
    "Ferrari|F8 Tributo": ["Base"],
    "Ferrari|F430": ["Base", "Scuderia"],
    "Ferrari|F458": ["Italia", "Spider"],
    "Ferrari|FF": ["Base"],
    "Ferrari|Portofino": ["Base"],
    "Fiat|500": ["Pop", "Sport", "Lounge"],
    "Fiat|500X": ["Pop", "Sport", "Lounge"],
    "Fiat|500L": ["Pop", "Sport", "Lounge"],
    "Ford|Edge": ["SE", "SEL", "Limited", "ST"],
    "Ford|Escape": ["S", "SE", "SEL", "Titanium", "ST"],
    "Ford|Explorer": ["Base", "XLT", "Limited", "ST", "Platinum"],
    "Ford|F-150": ["Regular Cab", "SuperCrew", "SuperCab", "XL", "XLT", "Lariat", "King Ranch", "Platinum"],
    "Ford|Mustang": ["EcoBoost", "GT", "Mach 1", "Shelby GT500", "Dark Horse"],
    "Ford|Ranger": ["Regular Cab", "SuperCrew", "SuperCab", "XL", "XLT", "Lariat"],
    "Ford|Bronco": ["Base", "Big Bend", "Black Diamond", "Outer Banks", "Wildtrak"],
    "Genesis|G70": ["2.0T", "3.8", "G70 2.0T"],
    "Genesis|G80": ["2.0T", "3.8", "Electrified"],
    "Genesis|G90": ["3.8", "5.0", "Electrified"],
    "Genesis|GV70": ["2.5T", "3.8", "Electrified"],
    "Genesis|GV80": ["2.5T", "3.8"],
    "GMC|Acadia": ["SL", "SLE", "Denali", "AT4"],
    "GMC|Canyon": ["Base", "SLE", "Denali", "AT4"],
    "GMC|Sierra 1500": ["Regular", "Double Cab", "Crew Cab", "Denali", "AT4"],
    "GMC|Terrain": ["SL", "SLE", "SLT", "Denali"],
    "GMC|Yukon": ["SLE", "SLT", "Denali", "AT4"],
    "GMC|Yukon XL": ["SLE", "SLT", "Denali"],
    "Honda|Accord": ["LX", "Sport", "EX", "EX-L", "Touring", "Hybrid"],
    "Honda|Civic": ["LX", "Sport", "EX", "EX-T", "Touring", "Si", "Type R", "Hybrid"],
    "Honda|CR-V": ["LX", "EX", "EX-L", "Touring", "Hybrid"],
    "Honda|Odyssey": ["LX", "EX", "EX-L", "Touring", "Elite"],
    "Honda|Pilot": ["LX", "EX", "EX-L", "Touring", "Elite", "Hybrid"],
    "Honda|Ridgeline": ["RT", "RTL", "RTL-E", "Black Edition"],
    "Honda|Fit": ["LX", "Sport", "EX"],
    "Honda|Insight": ["LX", "EX", "Touring"],
    "Hyundai|Accent": ["SE", "SEL", "Limited"],
    "Hyundai|Elantra": ["SE", "SEL", "Limited", "N", "Hybrid"],
    "Hyundai|Ioniq": ["SE", "SEL", "Limited", "Hybrid", "Plug-in Hybrid", "Electric"],
    "Hyundai|Kona": ["SE", "SEL", "Limited", "N Line", "Electric"],
    "Hyundai|Palisade": ["SE", "SEL", "Limited", "Calligraphy"],
    "Hyundai|Santa Fe": ["SE", "SEL", "Limited", "Calligraphy"],
    "Hyundai|Sonata": ["SE", "SEL", "Limited", "N Line", "Hybrid", "Plug-in Hybrid"],
    "Hyundai|Tucson": ["SE", "SEL", "Limited", "N Line"],
    "Hyundai|Venue": ["SE", "SEL", "Limited"],
    "Infiniti|Q30": ["Base", "Premium"],
    "Infiniti|Q50": ["Pure", "Luxe", "Red Sport", "Eau Rouge"],
    "Infiniti|Q60": ["Pure", "Luxe", "Red Sport"],
    "Infiniti|Q70": ["Base", "Premium", "Signature"],
    "Infiniti|QX50": ["Pure", "Luxe", "Essential"],
    "Infiniti|QX60": ["Base", "Luxury"],
    "Infiniti|QX80": ["Base", "Luxury", "Platinum"],
    "Jaguar|F-Pace": ["Base", "Premium", "R-Sport", "SVR"],
    "Jaguar|F-Type": ["Base", "R", "SVR"],
    "Jaguar|I-Pace": ["Base", "SE", "HSE"],
    "Jaguar|XE": ["Base", "Premium", "R-Sport", "SVR"],
    "Jaguar|XF": ["Base", "Premium", "R-Sport", "SVR"],
    "Jeep|Cherokee": ["Sport", "Latitude", "Limited", "Trailhawk", "High Altitude"],
    "Jeep|Compass": ["Sport", "Latitude", "Limited", "Trailhawk"],
    "Jeep|Gladiator": ["Sport", "Overland", "Rubicon", "Mojave"],
    "Jeep|Grand Cherokee": ["Laredo", "Limited", "Limited X", "Trailhawk", "Summit", "High Altitude"],
    "Jeep|Renegade": ["Sport", "Latitude", "Limited", "Trailhawk"],
    "Jeep|Wrangler": ["Sport", "Sahara", "Rubicon", "Unlimited", "Willys"],
    "Kia|Forte": ["FE", "LX", "S", "EX", "GT"],
    "Kia|K5": ["LX", "EX", "SX", "SX Prestige"],
    "Kia|Niro": ["LX", "EX", "SX", "SX Prestige", "Hybrid", "Plug-in Hybrid"],
    "Kia|Rio": ["FE", "LX", "S", "EX"],
    "Kia|Seltos": ["LX", "EX", "SX"],
    "Kia|Sorento": ["L", "LX", "EX", "SX", "SX Prestige"],
    "Kia|Sportage": ["LX", "S", "EX", "SX"],
    "Kia|Stinger": ["Base", "GT", "GT2", "GT Lounge"],
    "Kia|Telluride": ["LX", "S", "EX", "SX", "SX Prestige"],
    "Kia|Sedona": ["LX", "EX", "SXL", "Limited"],
    "Lamborghini|Aventador": ["Base", "S", "SV", "SVJ"],
    "Lamborghini|Huracán": ["Base", "Performante", "Sterrato"],
    "Lamborghini|Urus": ["Base", "S", "Performante"],
    "Land Rover|Discovery": ["SE", "HSE", "Landmark"],
    "Land Rover|Discovery Sport": ["SE", "HSE", "R-Dynamic"],
    "Land Rover|Range Rover": ["Base", "Sport", "Vogue"],
    "Land Rover|Range Rover Evoque": ["Base", "HSE", "R-Dynamic"],
    "Land Rover|Range Rover Sport": ["SE", "HSE", "SVR"],
    "Land Rover|Range Rover Velar": ["Base", "HSE", "R-Dynamic"],
    "Lexus|ES": ["250", "300h", "350h", "F"],
    "Lexus|GS": ["350", "450h", "F"],
    "Lexus|IS": ["300", "350", "500", "F"],
    "Lexus|GX": ["460", "550"],
    "Lexus|LX": ["570"],
    "Lexus|LS": ["500", "500h", "F"],
    "Lexus|NX": ["250", "350", "350h", "450h+"],
    "Lexus|RX": ["350", "450h", "450h+", "500h"],
    "Lexus|UX": ["200", "250h", "250h AWD"],
    "Lincoln|Aviator": ["Premiere", "Select", "Reserve", "Black Label"],
    "Lincoln|Corsair": ["Premiere", "Select", "Reserve"],
    "Lincoln|MKZ": ["Premiere", "Select", "Reserve", "Black Label"],
    "Lincoln|Navigator": ["Premiere", "Select", "Reserve", "Black Label"],
    "Lincoln|Continental": ["Base", "Black Label"],
    "Lucid|Air": ["Pure", "Touring", "Grand Touring", "Sapphire"],
    "Maserati|Ghibli": ["Base", "S", "Trofeo"],
    "Maserati|Levante": ["Base", "S", "Trofeo"],
    "Maserati|Quattroporte": ["Base", "S", "Trofeo"],
    "Maserati|MC20": ["Base"],
    "Mazda|CX-3": ["Sport", "Touring", "Grand Touring"],
    "Mazda|CX-30": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|CX-50": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|CX-5": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|CX-9": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|Mazda2": ["Sport", "Select", "Preferred"],
    "Mazda|Mazda3": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|Mazda6": ["Base", "Select", "Preferred", "Premium"],
    "Mazda|MX-5 Miata": ["Sport", "Club", "Grand Touring"],
    "McLaren|570GT": ["Base"],
    "McLaren|570S": ["Base"],
    "McLaren|650S": ["Base"],
    "McLaren|720S": ["Base", "Performance"],
    "McLaren|765LT": ["Base"],
    "Mercedes-Benz|A-Class": ["A220", "A250", "AMG A35", "AMG A45"],
    "Mercedes-Benz|C-Class": ["C300", "C300 4MATIC", "C43 AMG", "C63 AMG"],
    "Mercedes-Benz|E-Class": ["E350", "E450", "E53 AMG", "E63 AMG"],
    "Mercedes-Benz|S-Class": ["S500", "S580", "AMG S63"],
    "Mercedes-Benz|G-Class": ["G550", "AMG G63"],
    "Mercedes-Benz|GLC": ["GLC300", "GLC43 AMG", "GLC63 AMG"],
    "Mercedes-Benz|GLE": ["GLE350", "GLE450", "GLE53 AMG"],
    "Mercedes-Benz|GLS": ["GLS450", "GLS580", "AMG GLS63"],
    "Mini|Clubman": ["Base", "Cooper", "Cooper S"],
    "Mini|Countryman": ["Base", "Cooper", "Cooper S"],
    "Mini|Hardtop": ["Base", "Cooper", "Cooper S"],
    "Mitsubishi|Eclipse": ["Base", "Cross"],
    "Mitsubishi|Outlander": ["ES", "SEL", "Limited", "Hybrid"],
    "Mitsubishi|Lancer": ["ES", "SEL", "Ralliart"],
    "Mitsubishi|Mirage": ["Base", "ES", "SEL"],
    "Nissan|Altima": ["S", "SV", "SL", "Platinum", "SR Turbo"],
    "Nissan|Leaf": ["S", "SV", "Plus", "SL"],
    "Nissan|Maxima": ["S", "SV", "SL", "Platinum"],
    "Nissan|Murano": ["S", "SV", "SL", "Platinum", "Hybrid"],
    "Nissan|Pathfinder": ["S", "SV", "SL", "Platinum"],
    "Nissan|Rogue": ["S", "SV", "SL", "Platinum"],
    "Nissan|Sentra": ["S", "SV", "SR", "SL"],
    "Nissan|Z": ["Base", "Performance"],
    "Polestar|1": ["Base"],
    "Polestar|2": ["Standard Range", "Long Range", "Performance"],
    "Polestar|3": ["Base", "Performance"],
    "Polestar|4": ["Base", "Performance"],
    "Porsche|911": ["Carrera", "Carrera S", "Carrera 4", "Turbo"],
    "Porsche|Cayenne": ["Base", "S", "Turbo", "E-Hybrid"],
    "Porsche|Macan": ["Base", "S", "Turbo"],
    "Porsche|Panamera": ["Base", "S", "Turbo", "E-Hybrid"],
    "Ram|1500": ["Tradesman", "SLT", "Laramie", "Rebel", "Limited", "Tungsten"],
    "Ram|2500": ["Tradesman", "Power Wagon", "SLT", "Laramie", "Limited"],
    "Ram|3500": ["Tradesman", "SLT", "Laramie"],
    "Renault|Clio": ["Base", "Interactive"],
    "Renault|Espace": ["Base", "Dynamique"],
    "Renault|Megane": ["Base", "Dynamique"],
    "Rivian|R1S": ["Dual Motor", "Quad Motor", "Tri Motor"],
    "Rivian|R1T": ["Dual Motor", "Quad Motor", "Tri Motor"],
    "Rolls-Royce|Ghost": ["Base", "Black Badge"],
    "Rolls-Royce|Phantom": ["Base", "Black Badge"],
    "Rolls-Royce|Cullinan": ["Base", "Black Badge"],
    "Saab|9-3": ["Base", "Sport"],
    "Saab|9-5": ["Base", "Aero"],
    "Subaru|Ascent": ["Base", "Premium", "Limited", "Touring"],
    "Subaru|BRZ": ["Base", "Premium", "Limited"],
    "Subaru|Crosstrek": ["Base", "Premium", "Sport", "Limited"],
    "Subaru|Forester": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Subaru|Impreza": ["Base", "Premium", "Sport", "Limited"],
    "Subaru|Legacy": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Subaru|Outback": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Subaru|WRX": ["Base", "Premium", "STI", "Limited"],
    "Suzuki|Swift": ["Base", "VXi", "ZXi"],
    "Suzuki|Vitara": ["Base", "SZ5"],
    "Suzuki|S-Cross": ["Base", "ZXi"],
    "Tata|Nexon": ["XE", "XM", "EV"],
    "Tata|Harrier": ["XE", "XM"],
    "Tesla|Model 3": ["Standard Range", "Long Range", "Performance", "Plaid"],
    "Tesla|Model S": ["Long Range", "Performance", "Plaid"],
    "Tesla|Model X": ["Long Range", "Performance", "Plaid"],
    "Tesla|Model Y": ["RWD", "Long Range", "Performance"],
    "Toyota|Camry": ["LE", "SE", "XLE", "TRD", "Hybrid LE", "Hybrid SE", "Hybrid XLE"],
    "Toyota|Corolla": ["L", "LE", "SE", "XLE", "GR", "Hybrid LE", "Hybrid SE"],
    "Toyota|GR Supra": ["2.0", "3.0"],
    "Toyota|RAV4": ["LE", "XLE", "Adventure", "TRD", "Prime LE", "Prime XLE"],
    "Toyota|Highlander": ["L", "LE", "XLE", "Limited", "Platinum", "Hybrid LE"],
    "Toyota|Prius": ["LE", "XLE", "Limited", "Prime LE", "Prime XLE"],
    "Toyota|4Runner": ["SR5", "TRD", "TRD Pro", "Limited"],
    "Toyota|Tacoma": ["SR", "SR5", "TRD", "Limited"],
    "Toyota|Tundra": ["SR", "SR5", "Limited", "Platinum"],
    "Toyota|Sienna": ["LE", "XLE", "Limited", "Platinum", "Hybrid"],
    "Volkswagen|Golf": ["S", "SE", "SEL", "GTI", "R"],
    "Volkswagen|Jetta": ["S", "SE", "SEL", "GLI"],
    "Volkswagen|Passat": ["S", "SE", "SEL", "GLI"],
    "Volkswagen|Tiguan": ["S", "SE", "SEL", "R-Line"],
    "Volkswagen|Atlas": ["S", "SE", "SEL", "R-Line"],
    "Volkswagen|ID.4": ["Standard", "Pro", "Pro Max"],
    "Volkswagen|ID.5": ["Standard", "Pro", "Pro Max"],
    "Volvo|S60": ["Momentum", "Inscription", "R-Design", "Polestar"],
    "Volvo|S90": ["Momentum", "Inscription", "R-Design"],
    "Volvo|XC40": ["Momentum", "Inscription", "R-Design", "Recharge"],
    "Volvo|XC60": ["Momentum", "Inscription", "R-Design", "Polestar", "Recharge"],
    "Volvo|XC90": ["Momentum", "Inscription", "R-Design", "Recharge"],
    "Xpeng|G9": ["Base", "Plus", "Max"],
    "Xpeng|P7": ["Base", "Plus", "Max"],
    "Xpeng|P8": ["Base", "Plus", "Max"],
}

ENGINES = {
    "Acura|ILX": ["2.0L 4-Cyl", "2.4L Turbo"],
    "Acura|MDX": ["3.5L V6", "3.0L Turbo"],
    "Acura|RDX": ["2.0L Turbo", "3.5L V6"],
    "Acura|TLX": ["2.4L Turbo", "3.5L V6"],
    "Acura|NSX": ["3.5L Twin-Turbo Hybrid"],
    "Alfa Romeo|Giulia": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Alfa Romeo|Stelvio": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Alfa Romeo|4C": ["1.7L Turbo"],
    "Aston Martin|DB11": ["5.2L Twin-Turbo V12", "5.2L Twin-Turbo"],
    "Aston Martin|Vantage": ["4.0L Twin-Turbo V8"],
    "Aston Martin|Rapide": ["5.9L V12"],
    "Aston Martin|DBX": ["4.0L Twin-Turbo"],
    "Audi|A3": ["2.0L Turbo 4-Cyl"],
    "Audi|A4": ["2.0L Turbo", "3.0L TFSI", "2.9L Twin-Turbo"],
    "Audi|A6": ["3.0L TFSI", "2.9L Twin-Turbo"],
    "Audi|Q3": ["2.0L Turbo", "2.5L TFSI"],
    "Audi|Q5": ["2.0L Turbo", "3.0L TFSI", "2.9L Twin-Turbo"],
    "Audi|Q7": ["3.0L TFSI", "2.9L Twin-Turbo"],
    "Audi|A8": ["3.0L TFSI", "4.0L Twin-Turbo"],
    "Bentley|Continental": ["6.0L Twin-Turbo W12"],
    "Bentley|Mulsanne": ["6.75L Twin-Turbo V8"],
    "Bentley|Bentayga": ["6.0L Twin-Turbo W12", "4.0L Twin-Turbo V8"],
    "BMW|3 Series": ["2.0L Turbo", "3.0L Turbo", "3.0L Twin-Turbo"],
    "BMW|5 Series": ["2.0L Turbo", "3.0L Turbo", "4.4L Twin-Turbo"],
    "BMW|7 Series": ["3.0L Turbo", "4.4L Twin-Turbo"],
    "BMW|X1": ["2.0L Turbo", "3.0L Turbo"],
    "BMW|X3": ["2.0L Turbo", "3.0L Turbo"],
    "BMW|X5": ["3.0L Turbo", "4.4L Twin-Turbo"],
    "BMW|X7": ["3.0L Turbo", "4.4L Twin-Turbo"],
    "Bugatti|Chiron": ["8.0L Quad-Turbo W16"],
    "Bugatti|Veyron": ["8.0L Quad-Turbo W16"],
    "Buick|Regal": ["2.0L Turbo", "3.6L V6"],
    "Buick|LaCrosse": ["3.5L V6", "3.6L V6"],
    "Buick|Envision": ["2.0L Turbo", "2.5L 4-Cyl"],
    "Buick|Encore": ["1.4L Turbo", "1.5L 4-Cyl"],
    "Buick|Enclave": ["3.6L V6"],
    "Cadillac|CT4": ["2.0L Turbo", "3.6L V6"],
    "Cadillac|CT5": ["2.0L Turbo", "3.6L V6", "3.0L Turbo"],
    "Cadillac|CT6": ["2.0L Turbo", "3.6L V6"],
    "Cadillac|Escalade": ["5.3L V8", "6.2L V8"],
    "Cadillac|XT4": ["2.0L Turbo", "2.5L 4-Cyl"],
    "Cadillac|XT5": ["2.0L Turbo", "3.6L V6"],
    "Cadillac|XT6": ["3.6L V6"],
    "Chevrolet|Blazer": ["2.0L Turbo", "3.6L V6"],
    "Chevrolet|Camaro": ["2.0L Turbo", "3.6L V6", "6.2L V8", "6.2L Supercharged V8"],
    "Chevrolet|Colorado": ["2.5L 4-Cyl", "3.6L V6", "2.7L Turbo"],
    "Chevrolet|Corvette": ["5.2L V8", "5.5L V8", "5.5L Twin-Turbo"],
    "Chevrolet|Cruze": ["1.4L Turbo", "1.5L Turbo"],
    "Chevrolet|Equinox": ["1.5L Turbo", "2.0L Turbo"],
    "Chevrolet|Malibu": ["1.5L Turbo", "2.0L Turbo"],
    "Chevrolet|Silverado 1500": ["5.3L V8", "6.2L V8", "3.0L Turbo Diesel"],
    "Chevrolet|Traverse": ["3.6L V6"],
    "Chevrolet|Tahoe": ["5.3L V8", "6.2L V8", "3.0L Turbo Diesel"],
    "Chrysler|300": ["3.6L V6", "5.7L V8"],
    "Chrysler|Pacifica": ["3.6L V6"],
    "Chrysler|Prowler": ["3.5L V6"],
    "Citroen|C3": ["1.2L Turbo", "1.5L Diesel"],
    "Citroen|C4": ["1.2L Turbo", "1.5L Diesel"],
    "Citroen|C5": ["1.6L Turbo", "2.0L Diesel"],
    "Dodge|Charger": ["3.6L V6", "5.7L V8", "6.4L V8", "6.2L Supercharged"],
    "Dodge|Challenger": ["3.6L V6", "5.7L V8", "6.4L V8", "6.2L Supercharged"],
    "Dodge|Durango": ["3.6L V6", "5.7L V8", "6.4L V8"],
    "Dodge|Journey": ["2.4L 4-Cyl", "3.6L V6"],
    "Ferrari|F8 Tributo": ["3.9L Twin-Turbo V8"],
    "Ferrari|F430": ["4.3L V8"],
    "Ferrari|F458": ["4.5L V8"],
    "Ferrari|FF": ["6.3L V12"],
    "Ferrari|Portofino": ["3.9L Twin-Turbo V8"],
    "Fiat|500": ["1.2L 4-Cyl", "0.9L Turbo"],
    "Fiat|500X": ["1.4L Turbo", "1.6L Diesel"],
    "Fiat|500L": ["1.4L Turbo", "1.3L Turbo Diesel"],
    "Ford|Edge": ["2.0L Turbo", "2.7L Turbo"],
    "Ford|Escape": ["1.5L Turbo", "2.0L Turbo", "1.6L Turbo Diesel"],
    "Ford|Explorer": ["2.3L Turbo", "3.0L Turbo", "3.3L V6"],
    "Ford|F-150": ["3.3L V6", "5.0L V8", "3.5L EcoBoost", "2.7L EcoBoost", "3.0L EcoBoost Turbo Diesel"],
    "Ford|Mustang": ["2.3L EcoBoost", "5.0L V8", "5.2L V8"],
    "Ford|Ranger": ["2.3L Turbo", "3.0L Power Stroke Diesel", "2.7L Turbo"],
    "Ford|Bronco": ["2.3L Turbo", "3.0L Turbo"],
    "Genesis|G70": ["2.0L Twin-Turbo", "3.8L V6"],
    "Genesis|G80": ["2.0L Twin-Turbo", "3.8L V6", "Electric"],
    "Genesis|G90": ["3.8L V6", "5.0L V8", "Electric"],
    "Genesis|GV70": ["2.5L Turbo", "3.8L V6", "Electric"],
    "Genesis|GV80": ["2.5L Turbo", "3.8L V6"],
    "GMC|Acadia": ["2.0L Turbo", "3.6L V6"],
    "GMC|Canyon": ["2.5L 4-Cyl", "3.6L V6", "2.8L Duramax Diesel"],
    "GMC|Sierra 1500": ["5.3L V8", "6.2L V8", "3.0L Turbo Diesel"],
    "GMC|Terrain": ["1.5L Turbo", "2.0L Turbo"],
    "GMC|Yukon": ["5.3L V8", "6.2L V8", "3.0L Turbo Diesel"],
    "GMC|Yukon XL": ["5.3L V8", "6.2L V8"],
    "Honda|Accord": ["1.5L Turbo", "2.0L Turbo", "2.0L Hybrid"],
    "Honda|Civic": ["2.0L 4-Cyl", "1.5L Turbo", "2.0L Turbo", "2.0L Hybrid"],
    "Honda|CR-V": ["1.5L Turbo", "2.0L Turbo", "2.0L Hybrid"],
    "Honda|Odyssey": ["3.5L V6"],
    "Honda|Pilot": ["3.5L V6", "3.5L Hybrid"],
    "Honda|Ridgeline": ["3.5L V6"],
    "Honda|Fit": ["1.5L 4-Cyl"],
    "Honda|Insight": ["1.5L Hybrid"],
    "Hyundai|Accent": ["1.6L 4-Cyl", "1.5L Turbo"],
    "Hyundai|Elantra": ["2.0L 4-Cyl", "1.6L Turbo", "1.8L Hybrid"],
    "Hyundai|Ioniq": ["1.6L Hybrid", "1.6L Plug-in Hybrid", "Electric Motor"],
    "Hyundai|Kona": ["2.0L 4-Cyl", "1.6L Turbo", "Electric Motor"],
    "Hyundai|Palisade": ["2.2L Diesel", "3.8L V6"],
    "Hyundai|Santa Fe": ["2.5L 4-Cyl", "2.2L Diesel", "2.5L Turbo"],
    "Hyundai|Sonata": ["2.5L 4-Cyl", "2.0L Turbo", "2.0L Hybrid", "2.0L Plug-in Hybrid"],
    "Hyundai|Tucson": ["2.0L 4-Cyl", "1.6L Turbo", "2.5L Turbo"],
    "Hyundai|Venue": ["1.6L 4-Cyl"],
    "Infiniti|Q30": ["2.0L Turbo", "2.2L Diesel"],
    "Infiniti|Q50": ["2.0L Turbo", "3.0L Twin-Turbo", "3.7L V6"],
    "Infiniti|Q60": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Infiniti|Q70": ["3.5L V6", "3.7L V6"],
    "Infiniti|QX50": ["2.0L Turbo", "3.7L V6"],
    "Infiniti|QX60": ["3.5L V6"],
    "Infiniti|QX80": ["5.6L V8"],
    "Jaguar|F-Pace": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Jaguar|F-Type": ["2.0L Turbo", "3.0L Supercharged", "5.0L Supercharged"],
    "Jaguar|I-Pace": ["Electric Motor"],
    "Jaguar|XE": ["2.0L Turbo", "3.0L Supercharged"],
    "Jaguar|XF": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Jeep|Cherokee": ["2.0L Turbo", "3.2L V6", "3.5L V6"],
    "Jeep|Compass": ["2.0L Turbo", "1.6L Turbo Diesel"],
    "Jeep|Gladiator": ["3.6L V6", "2.0L Turbo Diesel"],
    "Jeep|Grand Cherokee": ["3.6L V6", "5.7L V8", "3.0L Turbo Diesel", "3.0L Twin-Turbo Diesel"],
    "Jeep|Renegade": ["1.3L Turbo", "1.4L Turbo", "1.6L Turbo Diesel"],
    "Jeep|Wrangler": ["2.0L Turbo", "3.6L V6", "2.0L Turbo Diesel"],
    "Kia|Forte": ["2.0L 4-Cyl", "1.6L Turbo"],
    "Kia|K5": ["2.5L 4-Cyl", "2.0L Turbo", "3.3L Turbo"],
    "Kia|Niro": ["2.0L 4-Cyl", "1.6L Turbo", "Hybrid 1.6L", "Plug-in Hybrid 1.6L"],
    "Kia|Rio": ["1.6L 4-Cyl"],
    "Kia|Seltos": ["2.0L 4-Cyl"],
    "Kia|Sorento": ["2.5L 4-Cyl", "2.2L Diesel", "3.3L Turbo"],
    "Kia|Sportage": ["2.0L 4-Cyl", "2.0L Turbo", "2.2L Diesel"],
    "Kia|Stinger": ["2.0L Turbo", "3.8L V6"],
    "Kia|Telluride": ["3.8L V6"],
    "Kia|Sedona": ["3.8L V6", "2.2L Diesel"],
    "Lamborghini|Aventador": ["6.5L V12"],
    "Lamborghini|Huracán": ["5.2L V10"],
    "Lamborghini|Urus": ["4.0L Twin-Turbo V8"],
    "Land Rover|Discovery": ["2.0L Turbo", "3.0L Supercharged", "2.0L Diesel"],
    "Land Rover|Discovery Sport": ["2.0L Turbo", "2.0L Diesel"],
    "Land Rover|Range Rover": ["3.0L Supercharged", "5.0L V8", "3.0L Turbo Diesel"],
    "Land Rover|Range Rover Evoque": ["2.0L Turbo", "2.0L Diesel"],
    "Land Rover|Range Rover Sport": ["3.0L Supercharged", "5.0L V8", "3.0L Turbo Diesel"],
    "Land Rover|Range Rover Velar": ["2.0L Turbo", "3.0L Supercharged", "2.0L Diesel"],
    "Lexus|ES": ["2.5L 4-Cyl", "2.5L Hybrid", "3.5L Hybrid"],
    "Lexus|GS": ["3.5L V6", "3.5L Hybrid"],
    "Lexus|IS": ["2.0L Turbo", "3.5L V6", "5.0L V8"],
    "Lexus|GX": ["4.6L V8", "5.7L V8"],
    "Lexus|LX": ["5.7L V8"],
    "Lexus|LS": ["3.5L Twin-Turbo", "3.5L Hybrid"],
    "Lexus|NX": ["2.5L 4-Cyl", "3.5L V6", "Hybrid 2.5L"],
    "Lexus|RX": ["3.5L V6", "3.5L Hybrid"],
    "Lexus|UX": ["2.0L 4-Cyl", "Hybrid 2.5L"],
    "Lincoln|Aviator": ["3.0L Twin-Turbo", "2.5L Plug-in Hybrid"],
    "Lincoln|Corsair": ["2.3L Turbo", "2.0L Turbo", "2.5L Plug-in Hybrid"],
    "Lincoln|MKZ": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Lincoln|Navigator": ["3.5L Twin-Turbo"],
    "Lincoln|Continental": ["3.7L V6", "3.0L Twin-Turbo"],
    "Lucid|Air": ["Electric Motor Single", "Electric Motor Dual", "Electric Motor Tri"],
    "Maserati|Ghibli": ["3.0L Twin-Turbo", "3.8L V8"],
    "Maserati|Levante": ["3.0L Twin-Turbo", "3.8L V8"],
    "Maserati|Quattroporte": ["3.0L Twin-Turbo", "3.8L V8"],
    "Maserati|MC20": ["3.0L Twin-Turbo V6"],
    "Mazda|CX-3": ["2.0L 4-Cyl"],
    "Mazda|CX-30": ["2.0L 4-Cyl"],
    "Mazda|CX-50": ["2.5L 4-Cyl", "2.5L Turbo"],
    "Mazda|CX-5": ["2.5L 4-Cyl", "2.5L Turbo"],
    "Mazda|CX-9": ["2.5L Turbo"],
    "Mazda|Mazda2": ["1.5L 4-Cyl"],
    "Mazda|Mazda3": ["2.0L 4-Cyl", "2.5L 4-Cyl", "2.5L Turbo"],
    "Mazda|Mazda6": ["2.5L 4-Cyl", "2.5L Turbo"],
    "Mazda|MX-5 Miata": ["2.0L 4-Cyl", "2.5L 4-Cyl"],
    "McLaren|570GT": ["3.8L Twin-Turbo V8"],
    "McLaren|570S": ["3.8L Twin-Turbo V8"],
    "McLaren|650S": ["3.8L Twin-Turbo V8"],
    "McLaren|720S": ["4.0L Twin-Turbo V8"],
    "McLaren|765LT": ["4.0L Twin-Turbo V8"],
    "Mercedes-Benz|A-Class": ["2.0L Turbo", "2.0L Turbo"],
    "Mercedes-Benz|C-Class": ["2.0L Turbo", "4.0L Twin-Turbo"],
    "Mercedes-Benz|E-Class": ["2.0L Turbo", "3.0L Turbo", "4.0L Twin-Turbo"],
    "Mercedes-Benz|S-Class": ["3.0L Twin-Turbo", "4.0L Twin-Turbo"],
    "Mercedes-Benz|G-Class": ["4.0L Twin-Turbo"],
    "Mercedes-Benz|GLC": ["2.0L Turbo", "4.0L Twin-Turbo"],
    "Mercedes-Benz|GLE": ["2.0L Turbo", "3.0L Turbo", "4.0L Twin-Turbo"],
    "Mercedes-Benz|GLS": ["3.0L Turbo", "4.0L Twin-Turbo"],
    "Mini|Clubman": ["1.5L Turbo", "2.0L Turbo"],
    "Mini|Countryman": ["1.5L Turbo", "2.0L Turbo"],
    "Mini|Hardtop": ["1.5L Turbo", "2.0L Turbo"],
    "Mitsubishi|Eclipse": ["1.5L Turbo", "3.0L MIVEC"],
    "Mitsubishi|Outlander": ["2.4L 4-Cyl", "3.0L V6", "Hybrid"],
    "Mitsubishi|Lancer": ["2.0L 4-Cyl", "2.0L Turbo"],
    "Mitsubishi|Mirage": ["1.2L 3-Cyl"],
    "Nissan|Altima": ["2.5L 4-Cyl", "3.5L V6", "2.0L Turbo"],
    "Nissan|Leaf": ["Electric Motor 62kWh", "Electric Motor 110kWh"],
    "Nissan|Maxima": ["3.5L V6"],
    "Nissan|Murano": ["3.5L V6", "Hybrid 3.5L"],
    "Nissan|Pathfinder": ["3.5L V6"],
    "Nissan|Rogue": ["2.5L 4-Cyl"],
    "Nissan|Sentra": ["2.0L 4-Cyl"],
    "Nissan|Z": ["3.0L Twin-Turbo V6"],
    "Polestar|1": ["3.0L Twin-Turbo Hybrid"],
    "Polestar|2": ["Electric Motor Single", "Electric Motor Dual"],
    "Polestar|3": ["Electric Motor Dual"],
    "Polestar|4": ["Electric Motor Dual"],
    "Porsche|911": ["3.4L Twin-Turbo", "3.8L Twin-Turbo"],
    "Porsche|Cayenne": ["3.0L Turbo", "4.0L Twin-Turbo"],
    "Porsche|Macan": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Porsche|Panamera": ["3.0L Twin-Turbo", "4.0L Twin-Turbo"],
    "Ram|1500": ["3.6L V6", "5.7L V8", "3.0L EcoDiesel"],
    "Ram|2500": ["6.4L V8", "6.7L Cummins Diesel"],
    "Ram|3500": ["6.4L V8", "6.7L Cummins Diesel"],
    "Renault|Clio": ["1.2L Turbo", "1.0L Turbo"],
    "Renault|Espace": ["1.6L Turbo", "1.5L Diesel"],
    "Renault|Megane": ["1.2L Turbo", "1.5L Diesel"],
    "Rivian|R1S": ["Electric Motor Dual", "Electric Motor Quad"],
    "Rivian|R1T": ["Electric Motor Dual", "Electric Motor Quad"],
    "Rolls-Royce|Ghost": ["6.75L Twin-Turbo V12"],
    "Rolls-Royce|Phantom": ["6.75L Twin-Turbo V12"],
    "Rolls-Royce|Cullinan": ["6.75L Twin-Turbo V12"],
    "Saab|9-3": ["2.0L Turbo", "2.8L V6"],
    "Saab|9-5": ["2.3L Turbo", "3.0L V6"],
    "Subaru|Ascent": ["2.4L Turbo"],
    "Subaru|BRZ": ["2.4L Boxer"],
    "Subaru|Crosstrek": ["2.0L Boxer", "2.5L Turbo"],
    "Subaru|Forester": ["2.5L Boxer", "2.0L Turbo"],
    "Subaru|Impreza": ["2.0L Boxer"],
    "Subaru|Legacy": ["2.5L Boxer"],
    "Subaru|Outback": ["2.5L Boxer"],
    "Subaru|WRX": ["2.0L Turbo Boxer", "2.5L Turbo Boxer"],
    "Suzuki|Swift": ["1.2L 4-Cyl"],
    "Suzuki|Vitara": ["1.6L 4-Cyl", "1.4L Turbo"],
    "Suzuki|S-Cross": ["1.3L Turbo", "1.5L"],
    "Tata|Nexon": ["1.2L Turbo", "1.5L Diesel"],
    "Tata|Harrier": ["2.0L Diesel", "1.5L Turbo"],
    "Tesla|Model 3": ["Electric Motor Single", "Electric Motor Dual", "Electric Motor Tri"],
    "Tesla|Model S": ["Electric Motor Dual", "Electric Motor Tri"],
    "Tesla|Model X": ["Electric Motor Dual", "Electric Motor Tri"],
    "Tesla|Model Y": ["Electric Motor Single", "Electric Motor Dual"],
    "Toyota|Camry": ["2.5L 4-Cyl", "3.5L V6", "2.5L Hybrid"],
    "Toyota|Corolla": ["1.8L 4-Cyl", "2.0L 4-Cyl", "2.0L Hybrid"],
    "Toyota|GR Supra": ["2.0L Turbo", "3.0L Twin-Turbo"],
    "Toyota|RAV4": ["2.5L 4-Cyl", "2.5L Hybrid", "2.5L Plug-in Hybrid"],
    "Toyota|Highlander": ["3.5L V6", "3.5L Hybrid"],
    "Toyota|Prius": ["1.8L Hybrid", "1.8L Plug-in Hybrid"],
    "Toyota|4Runner": ["4.0L V6"],
    "Toyota|Tacoma": ["2.7L 4-Cyl", "3.5L V6"],
    "Toyota|Tundra": ["3.4L Twin-Turbo", "5.7L V8"],
    "Toyota|Sienna": ["2.5L Hybrid"],
    "Volkswagen|Golf": ["1.5L Turbo", "2.0L Turbo", "2.0L TSI"],
    "Volkswagen|Jetta": ["1.5L Turbo", "1.4L Turbo", "2.0L Turbo"],
    "Volkswagen|Passat": ["1.8L Turbo", "2.0L Turbo", "3.6L V6"],
    "Volkswagen|Tiguan": ["1.4L Turbo", "2.0L Turbo"],
    "Volkswagen|Atlas": ["2.0L Turbo", "3.6L V6"],
    "Volkswagen|ID.4": ["Electric Motor Single", "Electric Motor Dual"],
    "Volkswagen|ID.5": ["Electric Motor Single", "Electric Motor Dual"],
    "Volvo|S60": ["2.0L Turbo", "2.0L Turbo Hybrid"],
    "Volvo|S90": ["2.0L Turbo", "2.0L Turbo Hybrid"],
    "Volvo|XC40": ["2.0L Turbo", "2.0L Turbo Hybrid"],
    "Volvo|XC60": ["2.0L Turbo", "2.0L Turbo Hybrid"],
    "Volvo|XC90": ["2.0L Turbo", "2.0L Turbo Hybrid"],
    "Xpeng|G9": ["Electric Motor Single", "Electric Motor Dual"],
    "Xpeng|P7": ["Electric Motor Single", "Electric Motor Dual"],
    "Xpeng|P8": ["Electric Motor Single", "Electric Motor Dual"],
}

@app.get("/")
def root():
    return {"status": "ready"}

@app.get("/health")
def health():
    return {"status": "healthy"}

@app.get("/api/cars/makes")
def get_makes():
    return sorted(MAKES)

@app.get("/api/cars/models")
def get_models(make: str):
    return sorted(MODELS.get(make, []))

@app.get("/api/cars/trims")
def get_trims(make: str, model: str):
    key = f"{make}|{model}"
    return sorted(TRIMS.get(key, []))

@app.get("/api/cars/engines")
def get_engines(make: str, model: str):
    key = f"{make}|{model}"
    return sorted(ENGINES.get(key, []))

@app.get("/api/cars/colors")
def get_colors():
    return sorted(COLORS)

@app.get("/api/cars/decode-vin")
def decode_vin(vin: str):
    """Decode VIN using NHTSA API"""
    try:
        import requests
        
        vin = vin.strip().upper() if vin else ""
        
        if len(vin) < 17:
            return {"error": "Invalid VIN"}
        
        url = f"https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVin/{vin}?format=json"
        resp = requests.get(url, timeout=5)
        
        if resp.status_code != 200:
            return {"error": "Failed"}
        
        data = resp.json()
        results = data.get("Results", [])
        
        decoded = {}
        for r in results:
            var = r.get("Variable", "")
            val = r.get("Value", "")
            
            if var == "Model Year" and val:
                decoded["year"] = val
            elif var == "Make" and val:
                decoded["make"] = val
            elif var == "Model" and val:
                decoded["model"] = val
            elif var == "Fuel Type - Primary" and val:
                fuel = val.lower()
                if "gasoline" in fuel:
                    decoded["fuelType"] = "gasoline"
                elif "diesel" in fuel:
                    decoded["fuelType"] = "diesel"
                elif "hybrid" in fuel:
                    decoded["fuelType"] = "hybrid"
                elif "electric" in fuel:
                    decoded["fuelType"] = "electric"
        
        return decoded
        
    except Exception as e:
        return {"error": "VIN decode failed"}

@app.post("/api/leads/webhook/lead_received")
def lead_received(lead: LeadData):
    """Receive lead submission"""
    try:
        lead_id = f"LEAD_{lead.vin[:8]}"
        
        return {
            "success": True,
            "listing_id": lead_id,
            "ai_draft_offer": {
                "fair": 24500,
                "low": 22000,
                "max": 27000
            },
            "message": "Listing received successfully"
        }
    except Exception as e:
        return {"error": str(e)}
